# Uncomment the next line to define a global platform for your project
 platform :ios, '5.0'

target 'clothr' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'POPSUGARShopSense', :git => 'https://github.com/PopSugar/objc-POPSUGAR-ShopSense-client.git'
  # Pods for clothr

end
