# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

project 'clothr.xcodeproj'

target 'clothr' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for clothr
pod 'Parse'

end
